services:
  # Serviço do Backend
  api:
    build: ./manutenzio
    container_name: manutenzio-api
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=S3nh4-Sup3r-Segur4-Dificil-D3-Quebr4r-Docker
      - DB_USER=sa
      - DB_PASSWORD=
    networks:
      - manutenzio-network

  # Serviço do Frontend
  web:
    build: ./manutenzio-web
    container_name: manutenzio-web
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - manutenzio-network

networks:
  manutenzio-network:
    driver: bridge